import React from 'react'

const About = () => {
    return (
        <div className='about'>
            <p><h2>Red or What whas designet by Irigli Skenderi in an individual project work.</h2>
                Optimally housing and caring for a wine collection requires more than just a pretty room. Whether a household drinks 300 bottles a year or 30, an uninformed design layout can end up having a permanent effect on a home’s overall performance. Often, designers are not aware of the needs of wine collecting, resulting in storage and display that may be aesthetically pleasing, but does not preserve the bottles as they should or address a particular client’s drinking or entertaining style. But while most firms wouldn’t dream of installing a complex AV system on their own, and art consultancy is commonplace, approaching the niche knowledge behind wine collecting without direction often puts designers at a disadvantage.
                Especially, says Cameron Mahlstede, lead wine educator and consultant of Mahlstede Wines and former sommelier for Nancy Silverton's Osteria Mozza in Los Angeles, when there is still a good deal of bravado circulating around the grape-consuming community. He has an important word of advice for designers working with serious oenophiles: Get past the ego. “I don’t walk into my accountant’s office and tell him how to do my taxes,” he says, laughing, “but with people that love and purchase a great deal of wine, they often have a hard time stepping back, especially for established clients proud to be drinking wine longer than I’ve been alive. But that prevents a home from being truly elevated.”
                “I can only purchase for someone what they have the space for,” he explains, noting that “it’s much harder for a client to bolster a collection or fortify their long-term goals without the designer/consultant team.” A solid relationship between designer and consultant is an excellent way to finesse the needs of a collector now and into the future. Indeed, after a career working with chefs like Kevin Fink at Michelin-starred and James Beard Award–recognized restaurants, it is that one-on-one conversation that steered Mahlstede to private consultation.
                So what, exactly, does that discussion with a designer sound like? “I cede to the designer 100% stylistically, but a consultant will know what makes it functional,” he explains. “I’ve seen absolutely beautiful spaces that don’t line up with the client’s needs, especially those of considerable means that own multiple homes. The designer may have installed them all the same way, but the main house might have different needs than a secondary home.”
                Chad McPhail, of Los Angeles–based firm Jamie Bush + Co, consulted Mahlstede on one such house near Lake Tahoe, for a couple who does not consider themselves avid collectors. “It wasn’t that they love wine so much,” McPhail explained. “For them, it was about investment, both in accruing bottles and increasing the resale value of the house. They had no existing collection and we turned the conversation completely over to Cameron.”
                In turn, the wine consultant “looked at our rudimentary design for the space and did the math. He advised how many linear feet of shelving and coordinated the cooling system. It came out really slick,” McPhail confirms. “It’s definitely a serious showpiece of the house.” When the same clients began working with McPhail and Jamie Bush for their main residence in the Bay Area, they tapped into Mahlstede’s expertise once again. “I don’t tell a designer, ‘This should be stone or wood or glass,’” Mahlstede says. “My role is to explain what’s best for the wine and the client’s goals and execute that vision together. Spatially, I would advise the craftsperson building it out, ‘I need 1,500 spots for storage and 50 on a showcase.’”
            </p>
        </div>
    )
}

export default About